<?php

namespace ContainerC1DinhO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBartaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BartaController' shared autowired service.
     *
     * @return \App\Controller\BartaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4) . '/src/Controller/HauserController.php';

        $container->services['App\\Controller\\BartaController'] = $instance = new \App\Controller\BartaController();

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\BartaController', $container));

        return $instance;
    }
}
