<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZQzrxdO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZQzrxdO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZQzrxdO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZQzrxdO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZQzrxdO\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZQzrxdO',
    'container.build_id' => 'c6e50266',
    'container.build_time' => 1664178000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZQzrxdO');
