<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSldZuyu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSldZuyu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSldZuyu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSldZuyu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSldZuyu\App_KernelDevDebugContainer([
    'container.build_hash' => 'SldZuyu',
    'container.build_id' => 'dcf82c8f',
    'container.build_time' => 1663336614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSldZuyu');
