<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'homepage_add' => [[], ['_controller' => 'App\\Controller\\HauserController::add'], [], [['text', '/add']], [], [], []],
    'test_new' => [[], ['_controller' => 'App\\Controller\\TestController::new'], [], [['text', '/test_new']], [], [], []],
    'test_delete' => [[], ['_controller' => 'App\\Controller\\TestController::delete'], [], [['text', '/test_delete']], [], [], []],
    'test_edit' => [[], ['_controller' => 'App\\Controller\\TestController::edit'], [], [['text', '/test_edit']], [], [], []],
    'test_detail' => [[], ['_controller' => 'App\\Controller\\TestController::detail'], [], [['text', '/test_detail']], [], [], []],
    'test_default' => [[], ['_controller' => 'App\\Controller\\TestController::default'], [], [['text', '/test_default']], [], [], []],
    'homepage_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/homepage_new']], [], [], []],
    'homepage_delete' => [[], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['text', '/homepage_delete']], [], [], []],
    'homepage_edit' => [[], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/homepage_edit']], [], [], []],
    'homepage_detail' => [[], ['_controller' => 'App\\Controller\\UserController::detail'], [], [['text', '/homepage_detail']], [], [], []],
    'homepage_default' => [[], ['_controller' => 'App\\Controller\\UserController::default'], [], [['text', '/homepage_default']], [], [], []],
];
